// This file is auto-generated by Payload CMS (via `next build` / `payload generate:importMap`).
// The build process will overwrite it with actual component imports.
// Do not manually edit — add custom components via Payload config instead.
import type { ImportMap } from "payload";

export const importMap: ImportMap = {};
